spring:
  application:
    name: ExamsManager
  # 数据源的名称
  datasource:
    # 数据源的基本配置
    username: root
    password: 200004
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/graduationproject?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源的其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  redis:
    host: 192.168.48.129
    port: 6379
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false  # 页面不加载缓存，修改及时生效
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# mybatis的配置
mybatis:
    # 映射文件的位置
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
# 开启日志级别

#logging:
#  level:
#   web: debug

# pagehelper的配置
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


init:
  port: 8080
